// src/components/svelte/settings/SettingsApp.svelte
<script lang="ts">
import {
  PROFILES_COLLECTION_NAME,
  type Profile,
  parseProfile,
} from '@schemas/ProfileSchema';
import ProfileSection from '@shared/ProfileSection.svelte';
import { uid } from '@stores/session';
import { toClientEntry } from '@utils/client/entryUtils';
import { t } from '@utils/i18n';
import { logDebug } from '@utils/logHelpers';
import { onMount } from 'svelte';
import ProfileTool from './ProfileTool.svelte';

let profile: Profile | null = $state(null);

onMount(() => {
  logDebug('SettingsApp mounted', { uid: $uid });
  if ($uid === null) {
    window.location.href = '/login';
  }
  subscribe();
});

async function subscribe() {
  logDebug('SettingsApp subscribe', { uid: $uid });
  const { onSnapshot, doc, getFirestore } = await import('firebase/firestore');

  onSnapshot(doc(getFirestore(), PROFILES_COLLECTION_NAME, $uid), (doc) => {
    logDebug('SettingsApp onSnapshot', { doc: doc.data() });
    if (!doc.exists()) {
      return;
    }
    const p = parseProfile(toClientEntry(doc.data()), doc.id);
    profile = p;
  });
}
</script>

<div class="content-columns">
  {#if profile}
    <div>
      <h3>{t('settings:preview.title')}</h3>
      <ProfileSection {profile} />
    </div>
    <ProfileTool {profile} />
  {:else}
    <div>
      <cn-loader></cn-loader>
    </div>
  {/if}
</div>

// src/components/client/settings/SettingsApp/SettingsApp.tsx
import { WithAuth } from '@client/shared/WithAuth';
import { useStore } from '@nanostores/solid';
import { ProfileCard } from '@shared/ProfileCard';
import { $profile, $uid } from '@stores/session';
import { t } from '@utils/i18n';
import type { Component } from 'solid-js';
import { AuthzSection } from './AuthzSection';
import { ProfileSection } from './ProfileSection';
import { PublicProfileTool } from './PublicProfileTool';

export const SettingsApp: Component = () => {
  const profile = useStore($profile);
  const uid = useStore($uid);

  return (
    <WithAuth allow={!!uid()}>
      <div class="content-columns">
        <article>
          <ProfileCard profile={profile() || undefined} />
          <PublicProfileTool />
        </article>
        <article>
          <h2>{t('settings:personal.title')}</h2>
          <ProfileSection />
        </article>
        <article>
          <AuthzSection />
        </article>
      </div>
    </WithAuth>
  );
};
