// src/components/client/threads/ForkThreadApp/ForkThreadApp.tsx
/**
 * A solid-js editor form, takes in a thread and a reply, and allows the user to
 * create a new Thread from the reply.
 */

import { ProfileLink } from '@client/shared/ProfileLink';
import { WithLoader } from '@client/shared/WithLoader';
import { db } from '@firebase/client';
import { addReply } from '@firebase/client/threads/addReply';
import { useStore } from '@nanostores/solid';
import type { Reply } from '@schemas/ReplySchema';
import {
  THREADS_COLLECTION_NAME,
  type Thread,
  createThread,
} from '@schemas/ThreadSchema';
import { $topics } from '@stores/ThreadsApp/topics';
import { $uid, markEntrySeen } from '@stores/session';
import { pushSessionSnack } from '@utils/client/snackUtils';
import { toFirestoreEntry } from '@utils/client/toFirestoreEntry';
import { t } from '@utils/i18n';
import { logError } from '@utils/logHelpers';
import { addDoc, collection } from 'firebase/firestore';
import { type Component, For, createSignal } from 'solid-js';
import { MarkdownSection } from 'src/components/shared/MarkdownSection';

interface Props {
  thread: Thread;
  reply: Reply;
}

export const ForkThreadApp: Component<Props> = (props) => {
  const uid = useStore($uid);
  const [title, setTitle] = createSignal<string>(`Re: ${props.thread.title}`);
  const [topic, setTopic] = createSignal<string>(
    props.thread?.channel?.toLocaleLowerCase() ||
      props.thread.topic?.toLocaleLowerCase() ||
      'yleinen',
  );
  const topics = useStore($topics);
  const [markdownContent, setMarkdownContent] = createSignal<string>('');

  async function handleSubmit(e: Event) {
    e.preventDefault();
    const formData = new FormData(e.currentTarget as HTMLFormElement);
    const data = Object.fromEntries(formData.entries());

    const thread = createThread({
      owners: [uid()],
      ...data,
      quoteRef: `${props.reply.threadKey}/${props.reply.key}`,
    });

    try {
      const cleaned = toFirestoreEntry(thread);
      const key = (
        await addDoc(collection(db, THREADS_COLLECTION_NAME), cleaned)
      ).id;
      await markEntrySeen(key, Date.now());

      await addReply(
        props.thread,
        uid(),
        t('threads:fork.crossPost', {
          link: `/threads/${key}`,
        }),
        `${props.reply.key}`,
      );

      pushSessionSnack('snacks:threadCreated');
      window.location.href = `/threads/${key}`;
    } catch (err: unknown) {
      logError('ForkThreadApp', err);
      pushSessionSnack('snacks:threadCreateFailed');
    }
  }

  return (
    <WithLoader loading={!uid()}>
      <form class="content-editor" onsubmit={handleSubmit}>
        <div class="toolbar">
          <label class="grow">
            {t('entries:thread.title')}
            <input
              name="title"
              type="text"
              value={title()}
              onInput={(e) => setTitle(e.currentTarget.value)}
              placeholder={t('entries:thread.placeholders.title')}
            />
          </label>
          <label>
            {t('entries:thread.channel')}
            <select
              name="channel"
              value={topic()}
              onChange={(e) => setTopic(e.currentTarget.value)}
            >
              <For each={topics()}>
                {(topic) => <option value={topic.slug}>{topic.name}</option>}
              </For>
            </select>
          </label>
          <button type="button">
            <cn-icon noun="add" />
          </button>
        </div>

        <div>
          <p>{t('threads:fork.quoted')}</p>
          <div class="elevation-1 border-radius p-1 clip-after-3 secondary">
            <p class="m-0">
              <ProfileLink uid={props.reply.owners[0]} />
            </p>
            <p class="downscaled">
              <MarkdownSection content={props.reply.markdownContent} />
            </p>
          </div>
        </div>

        <div>
          <br />
        </div>

        <textarea
          name="markdownContent"
          value={markdownContent()}
          onInput={(e) => setMarkdownContent(e.currentTarget.value)}
          placeholder={t('entries:thread.placeholders.content')}
        />

        <div class="toolbar">
          <button type="reset" class="text">
            {t('actions:cancel')}
          </button>
          <button type="submit">
            <cn-icon noun="send" />
            <span>{t('actions:send')}</span>
          </button>
        </div>
      </form>
    </WithLoader>
  );
};

// src/components/svelte/thread-editor/ForkThreadApp.svelte
<script lang="ts">
import { CHANNEL_DEFAULT_SLUG, type Channels } from '@schemas/ChannelSchema';
import type { Reply } from '@schemas/ReplySchema';
import type { Thread } from '@schemas/ThreadSchema';
import { uid } from '@stores/session';
import MarkdownContent from '@svelte/app/MarkdownContent.svelte';
import ProfileLink from '@svelte/app/ProfileLink.svelte';
import { pushSnack } from '@utils/client/snackUtils';
import { extractTags } from '@utils/contentHelpers';
import { t } from '@utils/i18n';
import { logDebug, logError } from '@utils/logHelpers';
import type { CnEditor } from 'cn-editor/src/cn-editor';
import ChannelSelect from './ChannelSelect.svelte';
import { submitThreadUpdate } from './submitThreadUpdate';

interface Props {
  thread: Thread;
  reply: Reply;
  channels: Channels;
}
const { thread, reply, channels }: Props = $props();
let title = $state(`Re: ${thread.title}`);
let channel = $state(
  thread?.channel?.toLocaleLowerCase() || CHANNEL_DEFAULT_SLUG,
);
let markdownContent = $state('');
let saving = $state(false);
let changed = $state(false);

function reset() {
  title = `Re: ${thread.title}`;
  channel = thread?.channel?.toLocaleLowerCase() || CHANNEL_DEFAULT_SLUG;
  markdownContent = '';
}

async function onsubmit(e: Event) {
  e.preventDefault();
  if (saving || !changed) {
    return;
  }
  saving = true;
  logDebug('ForkThreadApp', 'onsubmit', e);
  const data: Partial<Thread> = {
    title,
    channel,
    markdownContent,
    quoteRef: thread.key,
    tags: extractTags(markdownContent),
    owners: [$uid],
  };

  saving = false;

  try {
    const slug = await submitThreadUpdate(data);
    saving = false;
    window.location.href = `/threads/${slug}`;
  } catch (error) {
    logError('Error saving thread', error);
    pushSnack(t('threads:editor.error.save'));
    saving = false;
  }
}

function onChannelChange(event: Event) {
  const select = event.target as HTMLSelectElement;
  const selectedChannel = select.value;
  if (selectedChannel !== channel) {
    handleChange();
  }
}
function onContentChange(event: Event) {
  const editor = event.target as CnEditor;
  markdownContent = editor.value;
  handleChange();
}
function onTitleChange(event: Event) {
  const input = event.target as HTMLInputElement;
  title = input.value;
  handleChange();
}

function handleChange() {
  changed = true;
}
</script>

<form class="content-editor" {onsubmit}>
  <div class="toolbar">
    <label class="grow">
      {t('entries:thread.title')}
      <input
        name="title"
        type="text"
        value={title}
        disabled={saving}
        oninput={onTitleChange}
        placeholder={t('entries:thread.placeholders.title')}
      />
    </label>
    <ChannelSelect 
      channels={channels}
      channelKey={channel}
      disabled={saving}
      onchange={onChannelChange}
    />
  </div>

  <div class="mb-2">
    <p>{t('threads:fork.quoted')}</p>
    <div class="elevation-1 border-radius p-1 clip-after-3 secondary">
      <p class="m-0">
        <ProfileLink uid={reply.owners[0]} />
      </p>
      <p class="downscaled">
        <MarkdownContent content={`${reply.markdownContent}`} />
      </p>
    </div>
  </div>

  <section class="grow">
    <cn-editor
      value={markdownContent}
      name="markdownContent"
      disabled={saving}
      oninput={onContentChange}
      placeholder={t('entries:thread.placeholders.content')}
    ></cn-editor>
  </section>

    <div class="toolbar">
      <button type="reset" class="text">
        {t('actions:cancel')}
      </button>
      <span>
        debug: {JSON.stringify({ changed, saving })}
      </span>
      <button type="submit">
        <cn-icon noun="send"></cn-icon>
        <span>{t('actions:send')}</span>
      </button>
    </div>
  </form>
