// src/components/svelte/sites/CreatePageForm.svelte
<script lang="ts">
import { addPage } from '@firebase/client/site/addPage';
import { createPage } from '@schemas/PageSchema';
import type { Site } from '@schemas/SiteSchema';
import { uid } from '@stores/session';
import { pushSessionSnack } from '@utils/client/snackUtils';
import { t } from '@utils/i18n';
import { logDebug } from '@utils/logHelpers';
import { toMekanismiURI } from '@utils/mekanismiUtils';
import MembersOnly from './MembersOnly.svelte';

/* Progressive enhancement for the creating a page for a site */

interface Props {
  site: Site;
  name?: string;
}
const { site, name }: Props = $props();

let title = $state(name || '');
const key = $derived.by(() => {
  logDebug('Derived key', { site, title });
  if (site.usePlainTextURLs) return toMekanismiURI(title);
  return '-';
});
const keyClash = $derived.by(() => {
  // If the site does not use plain text URLs, there can't be a clash
  if (!site.usePlainTextURLs) return undefined;

  // If the key is empty, there can't be a clash
  if (!key) return undefined;

  // If the key is already in use, there is a clash
  const clashingIndex =
    site.pageRefs?.findIndex((ref) => ref.key === key) ?? -1;
  return clashingIndex >= 0 ? true : undefined;
});

function setTitle(e: Event) {
  title = (e.target as HTMLInputElement).value;
}

async function onsubmit(e: Event) {
  e.preventDefault();

  const newPage = createPage(key || '', site.key);
  newPage.name = title;
  newPage.markdownContent = `# ${title}\n\n`;
  newPage.owners = [$uid];

  const slug = await addPage(
    site.key,
    newPage,
    site.usePlainTextURLs ? key : undefined,
  );

  pushSessionSnack(
    t('site:create.page.success', { key: `${site.key}/${slug}` }),
  );
  window.location.href = `/sites/${site.key}/${slug}`;
}

function cancel() {
  history.back();
}
</script>

<div class="content-columns">
  <MembersOnly {site}>
    <section>
      <h2>{t('site:create.page.title')}</h2>

      <form {onsubmit}>
        {#if name}
          <p>
            <i>{t('site:create.page.missing', { name: `${name}` })}</i>
          </p>
        {:else}
          <label>
            {t('entries:page.name')}
            <input
              data-error={keyClash}
              oninput={setTitle}
              type="text"
              name="title"
              value={title} />
          </label>
          
          {#if keyClash}
            <p class="error p-1">
              {t('site:create.page.duplicateKey', { key: `${site.key}/${key}` })}
            </p>
            <p class="downscaled">
              <a href={`/sites/${site.key}/${key}`}>{t('site:create.page.duplicateKeyLink')}</a>
            </p>
          {:else}
            <p class="mt-1 break-all">
              <code class="p-1">{`https://pelilauta.social/sites/${site.key}/${site.usePlainTextURLs ? key || '...' : '[auto]'}`}</code>
            </p>
          {/if}
        {/if}
        
        <div class="toolbar justify-end">
          <button type="button" class="text" onclick={cancel}>
            {t('actions:cancel')}
          </button>
          <button type="submit">
            <cn-icon noun="add"></cn-icon>
            <span>{t('actions:create.page')}</span>
          </button>
        </div>
      </form>

    </section>
  </MembersOnly>
</div>

// src/components/client/sites/PageApp/CreatePageForm.tsx
/**
 * This is a solid-js powered form for creating a new wikipage.
 */
import { WithAuth } from '@client/shared/WithAuth';
import { addPage } from '@firebase/client/site/addPage';
import { useStore } from '@nanostores/solid';
import { createPage } from '@schemas/PageSchema';
import type { Site } from '@schemas/SiteSchema';
import { $uid } from '@stores/session';
import { t } from '@utils/i18n';
import { toMekanismiURI } from '@utils/mekanismiUtils';
import type { Component } from 'solid-js';

interface CreatePageFormProps {
  site: Site;
  name?: string;
}

export const CreatePageForm: Component<CreatePageFormProps> = (props) => {
  const uid = useStore($uid);

  const allow = () => props.site.owners.includes(uid());

  function cancel() {
    history.back();
  }

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    const form = e.target as HTMLFormElement;
    const formData = new FormData(form);
    const name = formData.get('name') as string;

    const newPage = createPage(toMekanismiURI(name), props.site.key);
    newPage.name = name;
    newPage.markdownContent = `# ${name}\n\n`;
    newPage.owners = [uid()];
    // If customPageKeys is enabled, we need to check if the slug is already in use
    // Otherwise, we can just generate a slug at creation time
    const proposedSlug = props.site.customPageKeys
      ? toMekanismiURI(name)
      : undefined;
    const slug = await addPage(props.site.key, newPage, proposedSlug);

    window.location.href = `/sites/${props.site.key}/${slug}`;
  };

  function isMissing() {
    return (props.name?.length || 0) > 0;
  }

  return (
    <div class="content-columns">
      <WithAuth allow={allow()}>
        <form onSubmit={handleSubmit}>
          <h2>{t('site:create.page.title')}</h2>
          {isMissing() && (
            <p>
              <i>{t('site:create.page.missing', { name: `${props.name}` })}</i>
            </p>
          )}
          <label>
            {t('entries:page.name')}
            <input type="text" name="name" value={`${props.name}`} />
          </label>
          <div class="toolbar justify-end">
            <button type="button" class="text" onClick={cancel}>
              {t('actions:cancel')}
            </button>
            <button type="submit">
              <cn-icon noun="add" />
              <span>{t('actions:create.page')}</span>
            </button>
          </div>
        </form>
      </WithAuth>
    </div>
  );
};
