// src/components/svelte/sites/PageFabs.svelte
<script lang="ts">
import type { Site } from '@schemas/SiteSchema';
import { uid } from '@stores/sessionStore';
import { t } from '@utils/i18n';

interface Props {
  site: Site;
  pageKey: string;
}

const { site, pageKey }: Props = $props();

const visible = $derived.by(() => {
  if (site.owners.includes($uid)) return true;
  if (site.players.includes($uid)) return true;
  return false;
});
</script>

{#if visible}
  <a
    href={`/sites/${site.key}/create/page`}
    class="fab secondary small"
  >
    <cn-icon noun="add" small></cn-icon>
    <span class="sm-hidden">{t('actions:create.page')}</span>
  </a>
  <a
    href={`/sites/${site.key}/${pageKey}/edit`}
    class="fab"
  >
    <cn-icon noun="edit" small></cn-icon>
    <span class="sm-hidden">{t('actions:edit')}</span>
  </a>
{/if}

// src/components/client/sites/PageApp/PageFabs.tsx
import { useStore } from '@nanostores/solid';
import type { Site } from '@schemas/SiteSchema';
import { t } from '@utils/i18n';
import type { Component } from 'solid-js';
import { Portal } from 'solid-js/web';
import { $uid } from 'src/stores/sessionStore';

/**
 * Fabs available for the site owners and players
 */
export const PageFabs: Component<{ pageKey: string; site: Site }> = (props) => {
  const uid = useStore($uid);

  function editor() {
    return props.site.owners.includes(uid());
  }

  return (
    <>
      {editor() && (
        <Portal mount={document.querySelector('#fab-tray') || document.body}>
          <a
            href={`/sites/${props.site.key}/create/page`}
            class="fab secondary small"
          >
            <cn-icon noun="add" small />
            <span>{t('actions:create.page')}</span>
          </a>
          <a
            href={`/sites/${props.site.key}/${props.pageKey}/edit`}
            class="fab"
          >
            <cn-icon noun="edit" small />
            <span>{t('actions:edit')}</span>
          </a>
        </Portal>
      )}
    </>
  );
};
