// src/components/client/eula/EulaDialog.tsx
import type { CnDialog } from '@11thdeg/cyan-next';
import { createAccount } from '@firebase/client/account/createAccount';
import { updateAccount } from '@firebase/client/account/updateAccount';
import { createProfile } from '@firebase/client/profile/createProfile';
import { useStore } from '@nanostores/solid';
import type { Account } from '@schemas/AccountSchema';
import { pushSnack } from '@utils/client/snackUtils';
import { t } from '@utils/i18n';
import { logWarn } from '@utils/logHelpers';
import { toFid } from '@utils/toFid';
import { type Component, type JSX, createEffect, createSignal } from 'solid-js';
import { auth } from 'src/firebase/client';
import { generateUsername } from 'src/firebase/client/generateUsername';
import type { Profile } from 'src/schemas/ProfileSchema';
import { $profile, $requiresEula, $uid, logout } from 'src/stores/sessionStore';
import { ProfileCreationCard } from './ProfileCreationCard';

type DialogProps<P = Record<string, unknown>> = P & { children?: JSX.Element };

/**
 * This is a solid-js component, that displays a dialog, when there is a
 * logged in user, that has not accepted the EULA yet.
 *
 * Depending on the users profile status, it will either allow accepting
 * the EULA for an existing profile, or additionally create a new profile
 * for the user.
 */
export const EulaDialog: Component = (props: DialogProps) => {
  const [nickname, setNickname] = createSignal('');
  const [inValid, setInvalid] = createSignal(false);
  let dialog: HTMLDialogElement | undefined;

  const uid = useStore($uid);
  const openDialog = useStore($requiresEula);
  const legacyProdile = useStore($profile);

  // If the app wants to open this dialog, it needs to set the
  // $requiresEula store value to true
  createEffect(() => {
    if (openDialog()) {
      // Initialize the state, only if the eula is required
      initValues();
      dialog?.showModal();
    }
  });

  async function initValues() {
    if (legacyProdile().nick) {
      // The user has already accepted an earlier EULA, no need reset the nick.
      return;
    }
    const user = auth.currentUser;

    // Get an unique default nickname for the user
    const nickname = await generateUsername(
      user?.displayName || '',
      user?.email || '',
    );

    // Load the account data
    setNickname(nickname);
  }

  async function oncancel() {
    console.log('User declined the EULA, logging out');
    // When the user cancels the dialog, sign out
    await logout();
    (document.getElementById('eulaDialog') as CnDialog).close();
  }

  async function onaccept() {
    // Update Account data to DB
    const account: Partial<Account> = { eulaAccepted: true };
    try {
      await createAccount(account, uid());
      pushSnack(t('snacks:account.created'));
    } catch (error) {
      await updateAccount(account, uid());
      pushSnack(t('snacks:eula.accepted'));
    }

    // Assuming either of the above operations succeeded,
    // we can now create a profile for the user, if it does not
    // exist
    if (!legacyProdile().nick) {
      const profileData: Partial<Profile> = {};
      profileData.nick = nickname();
      if (auth.currentUser?.photoURL) {
        profileData.avatarURL = auth.currentUser.photoURL;
      }
      createProfile(profileData, uid());
      pushSnack(t('snacks:profile.created'));
    } else {
      logWarn('User has a profile, skipping profile creation');
    }

    // Close the dialog
    dialog?.close();
  }

  function avatarSrc() {
    return auth.currentUser?.photoURL || '';
  }

  function username() {
    return toFid(nickname());
  }

  return (
    <dialog ref={dialog}>
      <h2>{t('login:eula.title')}</h2>
      <section class="downscaled">{props.children}</section>
      {legacyProdile()?.nick ? null : (
        <ProfileCreationCard
          nickname={nickname()}
          setNickname={setNickname}
          setInvalid={setInvalid}
        />
      )}
      <div class="flex toolbar justify-end">
        <button type="button" class="text" onclick={oncancel}>
          {t('login:eula.decline')}
        </button>
        <button
          class="cta"
          disabled={inValid()}
          type="submit"
          onclick={onaccept}
        >
          {t('login:eula.accept')}
        </button>
      </div>
    </dialog>
  );
};

// src/components/svelte/eula/EulaDialog.svelte
<script lang="ts">
import { createAccount } from '@firebase/client/account/createAccount';
import { updateAccount } from '@firebase/client/account/updateAccount';
import { createProfile } from '@firebase/client/profile/createProfile';
import type { Account } from '@schemas/AccountSchema';
import type { Profile } from '@schemas/ProfileSchema';
import { uid } from '@stores/session';
import { requiresEula } from '@stores/session/account';
import { profile } from '@stores/session/profile';
import { pushSnack } from '@utils/client/snackUtils';
import { t } from '@utils/i18n';
import { logWarn } from '@utils/logHelpers';
import { toMekanismiURI } from '@utils/mekanismiUtils';
import { toFid } from '@utils/toFid';
import { type Snippet, onMount } from 'svelte';
import NickNameInput from './NickNameInput.svelte';

interface Props {
  children?: Snippet;
}
const { children }: Props = $props();
let dialog: HTMLDialogElement;
let nick = $state('');
let avararUrl = $state('');
const valid = $derived.by(() => {
  if ($profile?.nick) return true;
  return !!nick;
});
const handle = $derived.by(() => {
  if ($profile?.nick) return toFid($profile.nick);
  if (nick) return toFid(nick);
  return '–';
});

onMount(() => {
  const d = document.getElementById('eula-dialog');
  if (d) dialog = d as HTMLDialogElement;
  getUserInfo();
});

$effect(() => {
  $requiresEula && dialog.showModal();
});

async function getUserInfo() {
  const { getAuth } = await import('firebase/auth');
  const user = getAuth().currentUser;
  if (!user) return;
  avararUrl = user.photoURL || '';
  const dpn = user.displayName;
  const username = dpn ?? user.email?.split('@')[0];
  nick = toMekanismiURI(username || '');
}

async function handleSubmit(e: Event) {
  e.preventDefault();
  dialog.close();

  // Update Account data to DB
  const account: Partial<Account> = { eulaAccepted: true };
  try {
    await createAccount(account, $uid);
    pushSnack(t('snacks:account.created'));
  } catch (error) {
    await updateAccount(account, $uid);
    pushSnack(t('snacks:eula.accepted'));
  }

  // Assuming either of the above operations succeeded,
  // we can now create a profile for the user, if it does not
  // exist
  if (!$profile?.nick) {
    const profileData: Partial<Profile> = {};
    profileData.nick = nick;
    if (avararUrl) {
      profileData.avatarURL = avararUrl;
    }
    createProfile(profileData, $uid);
    pushSnack(t('snacks:profile.created'));
  } else {
    logWarn('User has a profile, skipping profile creation');
  }

  // Close the dialog
  dialog?.close();
}

async function handleCancel(e?: Event) {
  e?.preventDefault();
  const { signOut, getAuth } = await import('firebase/auth');
  await signOut(getAuth());
  dialog.close();
}

function setNick(n: string) {
  nick = n;
}
</script>

<dialog id="eula-dialog" class="eula-dialog">
  <h2>{t('login:eula.title')}</h2>
  <section class="downscaled">
    {@render children?.()}
  </section>
  <form onsubmit={handleSubmit}>
    <section class="elevation-3 border-radius p-2 mt-2">
    {#if $profile?.nick}
      <!-- LEGACY PROFILE UPGRADE -->
      <h3 class="downscaled mt-0">
        {t('login:eula.updateNotice.title')}
      </h3>
      <p class="text-small">
        {t('login:eula.updateNotice.description')}
      </p>
    {:else}
      <div class="flex flex-no-wrap">
        <cn-avatar nick={nick} src={avararUrl}></cn-avatar>
        <fieldset class="grow">
          <NickNameInput
            {nick}
            {setNick}
          />
          <p>
            <strong>{t('entries:profile.username')}: </strong>
            <span>{handle}</span>
          </p>
        </fieldset>
      </div>
      <p class="text-caption">{t('login:eula.profileInfo')}</p>
    {/if}
    </section>
    <div class="flex toolbar justify-end">
      <button type="button" class="text" onclick={handleCancel}>
        {t('login:eula.decline')}
      </button>
      <button
        class="cta"
        disabled={!valid}
        type="submit"
        >
      {t('login:eula.accept')}
    </button>
  </div>
  </form>
</dialog>
