// src/components/svelte/site-library/SiteCard.svelte
<script lang="ts">
import type { Site } from '@schemas/SiteSchema';
import { uid } from '@stores/sessionStore';
import { toDisplayString } from '@utils/contentHelpers';
import { systemToNoun } from '@utils/schemaHelpers';
interface Props {
  site: Site;
}
const { site }: Props = $props();
const owns = $derived(() => site.owners.includes($uid));
const plays = $derived(() => site.players?.includes($uid));
</script>
<cn-card
  title={site.name}
  href={`/sites/${site.key}`}
  noun={systemToNoun(site.system)}
  cover={site.posterURL || undefined}
>
  <p>{site.description}</p>
  <div slot="actions" class="flex toolbar">
    {#if owns()}
      <cn-icon noun="avatar"></cn-icon>
    {/if}
    {#if plays()}
      <cn-icon noun="adventurer"></cn-icon>
    {/if}
    <div>
      <p>{toDisplayString(site.flowTime)}</p>
    </div>
  </div>
</cn-card>

// src/components/client/sites/SiteCard.tsx
import { useStore } from '@nanostores/solid';
import type { Site } from '@schemas/SiteSchema';
import { toDisplayString } from '@utils/contentHelpers';
import { systemToNoun } from '@utils/schemaHelpers';
import { type Component, createMemo } from 'solid-js';
import { $uid } from 'src/stores/sessionStore';

export const SiteCard: Component<Site> = (props) => {
  const uid = useStore($uid);

  const owns = createMemo(() => props.owners.includes(uid()));
  const plays = createMemo(() => props.players?.includes(uid()));

  return (
    <cn-card
      href={`/sites/${props.key}`}
      noun={systemToNoun(props.system)}
      title={props.name}
      cover={props.posterURL || undefined}
    >
      <p>{props.description}</p>
      <div slot="actions" class="flex toolbar">
        {owns() && <cn-icon noun="avatar" />}
        {plays() && <cn-icon noun="adventurer" />}
        <div class="grow" />
        <p>{toDisplayString(props.flowTime)}</p>
      </div>
    </cn-card>
  );
};
