// src/components/client/sites/SiteOwnerToken.tsx
/**
 * A Solid-JS client side icon for site owner token
 *
 * Visible if the $uid is part of the props.site.owners array
 */
import { useStore } from '@nanostores/solid';
import type { Site } from '@schemas/SiteSchema';
import { $uid } from '@stores/sessionStore';
import type { Component } from 'solid-js';

export const SiteOwnerToken: Component<Site> = (props) => {
  const uid = useStore($uid);

  function visible() {
    return props.owners.includes(uid());
  }

  return <>{visible() && <cn-icon noun="avatar" small />}</>;
};

// src/components/svelte/sites/SiteOwnerToken.svelte
<script lang="ts">
import type { Site } from '@schemas/SiteSchema';
import { uid } from '@stores/sessionStore';

interface Props {
  site: Site;
}

const { site } = $props() as Props;
const owns = $derived(site.owners.includes($uid));
</script>
{#if owns}
<cn-icon noun="avatar" small></cn-icon>
{/if}
