// src/components/svelte/admin/AdminNavigationButton.svelte
<script lang="ts">
import { isAdmin } from '@stores/metaStore/metaStore';
import { uid } from '@stores/session';

const visible = $derived.by(() => {
  return isAdmin($uid);
});
</script>
{#if visible}
  <a href="/admin" aria-label="Admin">
    <cn-navigation-icon noun="admin" label="Admin"></cn-navigation-icon>
  </a>
{/if}

// src/components/client/navigation/AdminNavigationButton.tsx
/**
 * A solid-js wrapper component for <cn-navigation-icon> web component.
 *
 * Hidden unless the user has the admin role.
 */

import { useStore } from '@nanostores/solid';
import { isAdmin } from '@stores/metaStore/metaStore';
import { $uid } from '@stores/session';

export const AdminNavigationButton = () => {
  const uid = useStore($uid);
  const visible = () => isAdmin(uid());

  return visible() ? (
    <a href="/admin">
      <cn-navigation-icon noun="admin" label="Admin" />
    </a>
  ) : null;
};
