// src/components/svelte/inbox/NotificationItem.svelte
<script lang="ts">
import { markRead } from '@firebase/client/inbox/markRead';
import type { Notification } from '@schemas/NotificationSchema';
import ProfileLink from '@svelte/app/ProfileLink.svelte';
import { toDisplayString } from '@utils/contentHelpers';
import { t } from '@utils/i18n';

/**
 * A Line item in the notifications list.
 */
interface Props {
  notification: Notification;
}
const { notification }: Props = $props();

const noun = $derived.by(() => {
  if (notification.targetType.endsWith('.loved')) return 'love';
  if (notification.targetType.endsWith('.reply')) return 'discussion';
  return 'info';
});

const href = $derived.by(() => {
  if (notification.targetType === 'thread.loved')
    return `/threads/${notification.targetKey}`;
});

async function read() {
  markRead(notification.key, true);
}
</script>

<article
  class={`notification-item flex flex-no-wrap mb-1 p-1 border-radius ${notification.read ? '' : 'elevation-4'}`}>
  <cn-icon {noun} small class="mt-1"></cn-icon>
  <div class="grow">
    <p class="m-0">
      <ProfileLink uid={notification.from} />
      {t(`social:notification.${notification.targetType}`)}
    </p>
    <p class="m-0">
      <a {href}>{notification.targetTitle}</a>
    </p>
    <p class="m-0 text-caption">
      {toDisplayString(notification.createdAt)}
    {notification.targetType}
    </p>
  </div>

  {#if !notification.read}
  <button class="text" onclick={read} aria-label={t('actions:markRead')}>
    <cn-icon noun="check"></cn-icon>
  </button>
  {/if}
</article>

<style>
.unread {
  background-color: red;
}
</style>

// src/components/client/SocialApp/NotificationItem.tsx
import { ProfileLink } from '@client/shared/ProfileLink';
import type { Notification } from '@schemas/NotificationSchema';
import { updateNotification } from '@stores/SocialApp/notificationsStore';
import { t } from '@utils/i18n';
import { type Component, createMemo } from 'solid-js';

export const NotificationItem: Component<{ notification: Notification }> = (
  props,
) => {
  const notification = createMemo(() => props.notification);

  function parseNoun(notificationType: string) {
    const typeArray = notificationType.split('.');
    if (typeArray.length > 1) {
      const type = typeArray[1];
      if (type === 'loved') {
        return 'love';
      }
    }
    return 'send';
  }

  function markAsRead() {
    updateNotification({ read: true }, notification().key);
  }

  return (
    <div class="flex flex-no-wrap line-between">
      <cn-icon noun={parseNoun(notification().targetType)} class="no-shrink" />
      <div class="grow">
        <h4 class="downscaled m-0">
          <a href={`/threads/${notification().targetKey.split('/')[0]}`}>
            {`${notification().message}`}
          </a>
        </h4>
        <p class="mt-0">
          <ProfileLink uid={notification().from} />{' '}
          {t(`social:notification.${notification().targetType}`)}
        </p>
      </div>
      <button class="no-shrink" type="button" onclick={markAsRead}>
        <cn-icon noun="check" class="no-shrink" />
      </button>
    </div>
  );
};
