// src/components/svelte/threads/ThreadLikeButton.svelte
<script lang="ts">
import type { Thread } from '@schemas/ThreadSchema';
import { uid } from '@stores/session';
import { profile } from '@stores/session/profile';
import { loveThread, unloveThread } from '@stores/threadsStore/reactions';

interface Props {
  thread: Thread;
}
const { thread }: Props = $props();
const loves = $derived.by(
  () => $profile?.lovedThreads?.includes(thread.key) ?? false,
);
const count = $derived.by(() => thread?.lovedCount ?? 0);

function toggleLove() {
  if (loves) {
    loveThread($uid, thread.key);
  } else {
    unloveThread($uid, thread.key);
  }
}
</script>

<cn-reaction-button
  onClick={toggleLove}
  onKeyUp={(e: Event) => (e as KeyboardEvent).key === 'Enter' && toggleLove()}
  disabled={!$uid || undefined}
  {count}
  checked={loves}
  noun="love"
></cn-reaction-button>

// src/components/client/threads/ThreadLikeButton.tsx
/**
 * A simple wrapper arounf the "Like" button, that handles the liking of a thread
 *
 * (obviously, if the user is not logged in, the button will not do anything)
 */

import { useStore } from '@nanostores/solid';
import type { Thread } from '@schemas/ThreadSchema';
import { $profile, $uid } from '@stores/session';
import { type Component, createMemo } from 'solid-js';
import { loveThread, unloveThread } from 'src/stores/threadsStore/reactions';

export const ThreadLikeButton: Component<{ thread?: Thread }> = (props) => {
  const uid = useStore($uid);
  const profile = useStore($profile);

  const disabled = createMemo(
    () => !uid() || props.thread?.owners.includes(uid()),
  );

  const loves = createMemo(
    () => profile()?.lovedThreads?.includes(props.thread?.key || '') || false,
  );

  function toggleLove() {
    if (!props.thread) return;
    if (!loves()) {
      loveThread(uid(), props.thread.key);
    } else {
      unloveThread(uid(), props.thread.key);
    }
  }

  return (
    <cn-reaction-button
      onClick={toggleLove}
      onKeyUp={(e: Event) =>
        (e as KeyboardEvent).key === 'Enter' && toggleLove()
      }
      disabled={disabled()}
      count={props.thread?.lovedCount || 0}
      checked={loves()}
      noun="love"
    />
  );
};
